/*
 * generated by Xtext
 */
package org.verapdf.ui.contentassist

import org.verapdf.ui.contentassist.AbstractModelProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ModelProposalProvider extends AbstractModelProposalProvider {
}
