/*
* generated by Xtext
*/
package org.verapdf;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ModelStandaloneSetup extends ModelStandaloneSetupGenerated{

	public static void doSetup() {
		new ModelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

