/*
 * generated by Xtext
 */
package org.verapdf;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ModelRuntimeModule extends org.verapdf.AbstractModelRuntimeModule {

}
