/*
 * generated by Xtext
 */
package org.verapdf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ModelUiModule extends org.verapdf.ui.AbstractModelUiModule {

	public ModelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

}
